### ISSUE TITLE
Error when creating events if python version is 3.10

### ISSUE THREAD

**Issue by lexbailey** [allenporter/ical#455]
Creating an event causes the following error:

    AttributeError: module 'datetime' has no attribute 'UTC'

ical version 8.3.0

`datetime.UTC` was added in python 3.11, so this doesn't work in python 3.10, but ical claims to support 3.10
https://docs.python.org/3/library/datetime.html#datetime.UTC

Used here:
https://github.com/allenporter/ical/blob/d7d9f9a332ba02d3618746350ada3bff772d6208/ical/util.py#L23

it is just an alias to `datetime.timezone.utc`, which is available in python 3.10, so could just use that instead to maintain compatibility?

**Comment by allenporter** [comment]
Apologies, I should have explicitly removed support for python 3.10 when making that prior release. I'll address this and require 3.11 explicitly.

**Comment by allenporter** [comment]
This was changed when moving to support 3.13:
https://github.com/allenporter/ical/pull/445

**Comment by allenporter** [comment]
You may be able to keep using versions prior to 8.3.0. I've fixed 9.0.0 to correctly require 3.11.
